title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://idntliketobealone12-dot.github.io
baseurl: https://idntliketobealone12-dot.github.io/RAVERPG

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
